config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'unauthorized' => 'home#unauthorized'

  get 'home/license'

  resources :phase_roles
  resources :phases
  resources :sections
  resources :role_policies
  resources :recusals
  resources :uploads
  resources :divisions
  resources :departments
  resources :units
  resources :branches
  resources :colleges
  resources :schools
  resources :roles
  resources :user_roles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/branch.rb
class Branch < School
end

app/models/college.rb
class College < School
end

app/models/department.rb
class Department < Unit
end

app/models/division.rb
class Division < Unit
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :next_phase, class_name: 'Phase'
  has_one :previous_phase, as: :next_phase
  has_many :phase_roles
  has_many :roles, through: :phase_roles
end

app/models/phase_role.rb
class PhaseRole < ApplicationRecord
  belongs_to :phase
  belongs_to :role
end

app/models/recusal.rb
class Recusal < ApplicationRecord
  belongs_to :reviewer,  class_name: 'UserRole'
  belongs_to :candidate, class_name: 'UserRole'
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
  has_many :role_policies
  has_many :administrator_roles, through: :role_policies
  has_many :managed_roles, through: :role_policies
  has_many :phase_roles
  has_many :phases, through: :phase_roles
end

app/models/role_policy.rb
class RolePolicy < ApplicationRecord
  belongs_to :administrator_role, class_name: 'Role'
  belongs_to :managed_role, class_name: 'Role'
end

app/models/school.rb
class School < ApplicationRecord
  has_many :units
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :role
  has_many :uploads
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  belongs_to :section
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :uploads
  has_many :recusals, as: :reviewer
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
  has_many :role_policies, through: :role
  has_many :administrator_roles, through: :role_policies
  has_many :managed_roles, through: :role_policies
  belongs_to :unit, optional: true
  belongs_to :school, optional: true
  belongs_to :phase, optional: true

  def can_manage?(user)
    managed_roles.include?(user.role)
  end

  def admin?
    role.admin?
  end
end

app/controllers/phase_roles_controller.rb
class PhaseRolesController < ApplicationController
  before_action :set_phase_role, only: [:show, :edit, :update, :destroy]

  # GET /phase_roles
  # GET /phase_roles.json
  def index
    @phase_roles = PhaseRole.all
  end

  # GET /phase_roles/1
  # GET /phase_roles/1.json
  def show
  end

  # GET /phase_roles/new
  def new
    @phase_role = PhaseRole.new
  end

  # GET /phase_roles/1/edit
  def edit
  end

  # POST /phase_roles
  # POST /phase_roles.json
  def create
    @phase_role = PhaseRole.new(phase_role_params)

    respond_to do |format|
      if @phase_role.save
        format.html { redirect_to @phase_role, notice: 'Phase role was successfully created.' }
        format.json { render :show, status: :created, location: @phase_role }
      else
        format.html { render :new }
        format.json { render json: @phase_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phase_roles/1
  # PATCH/PUT /phase_roles/1.json
  def update
    respond_to do |format|
      if @phase_role.update(phase_role_params)
        format.html { redirect_to @phase_role, notice: 'Phase role was successfully updated.' }
        format.json { render :show, status: :ok, location: @phase_role }
      else
        format.html { render :edit }
        format.json { render json: @phase_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phase_roles/1
  # DELETE /phase_roles/1.json
  def destroy
    @phase_role.destroy
    respond_to do |format|
      format.html { redirect_to phase_roles_url, notice: 'Phase role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phase_role
      @phase_role = PhaseRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phase_role_params
      params.require(:phase_role).permit(:phase_id, :role_id)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phase_roles_helper.rb
module PhaseRolesHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/phase_roles/_form.html.erb
<%= form_for(phase_role) do |f| %>
  <% if phase_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phase_role.errors.count, "error") %> prohibited this phase_role from being saved:</h2>

      <ul>
      <% phase_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phase_id %>
    <%= f.text_field :phase_id %>
  </div>

  <div class="field">
    <%= f.label :role_id %>
    <%= f.text_field :role_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phase_roles/edit.html.erb
<h1>Editing Phase Role</h1>

<%= render 'form', phase_role: @phase_role %>

<%= link_to 'Show', @phase_role %> |
<%= link_to 'Back', phase_roles_path %>

app/views/phase_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phase Roles</h1>

<table>
  <thead>
    <tr>
      <th>Phase</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phase_roles.each do |phase_role| %>
      <tr>
        <td><%= phase_role.phase %></td>
        <td><%= phase_role.role %></td>
        <td><%= link_to 'Show', phase_role %></td>
        <td><%= link_to 'Edit', edit_phase_role_path(phase_role) %></td>
        <td><%= link_to 'Destroy', phase_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phase Role', new_phase_role_path %>

app/views/phase_roles/new.html.erb
<h1>New Phase Role</h1>

<%= render 'form', phase_role: @phase_role %>

<%= link_to 'Back', phase_roles_path %>

app/views/phase_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phase:</strong>
  <%= @phase_role.phase %>
</p>

<p>
  <strong>Role:</strong>
  <%= @phase_role.role %>
</p>

<%= link_to 'Edit', edit_phase_role_path(@phase_role) %> |
<%= link_to 'Back', phase_roles_path %>