config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'unauthorized' => 'home#unauthorized'

  get 'home/license'

  resources :phase_roles
  resources :phases
  resources :sections
  resources :role_policies
  resources :recusals
  resources :uploads
  resources :divisions
  resources :departments
  resources :units
  resources :branches
  resources :colleges
  resources :schools
  resources :roles
  resources :user_roles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/branch.rb
class Branch < School
end

app/models/college.rb
class College < School
end

app/models/department.rb
class Department < Unit
end

app/models/division.rb
class Division < Unit
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :next_phase, class_name: 'Phase'
  has_one :previous_phase, as: :next_phase
  has_many :phase_roles
  has_many :roles, through: :phase_roles
end

app/models/phase_role.rb
class PhaseRole < ApplicationRecord
  belongs_to :phase
  belongs_to :role
end

app/models/recusal.rb
class Recusal < ApplicationRecord
  belongs_to :reviewer,  class_name: 'UserRole'
  belongs_to :candidate, class_name: 'UserRole'
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
  has_many :role_policies
  has_many :administrator_roles, through: :role_policies
  has_many :managed_roles, through: :role_policies
  has_many :phase_roles
  has_many :phases, through: :phase_roles
end

app/models/role_policy.rb
class RolePolicy < ApplicationRecord
  belongs_to :administrator_role, class_name: 'Role'
  belongs_to :managed_role, class_name: 'Role'
end

app/models/school.rb
class School < ApplicationRecord
  has_many :units
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :role
  has_many :uploads
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  belongs_to :section
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :uploads
  has_many :recusals, as: :reviewer
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
  has_many :role_policies, through: :role
  has_many :administrator_roles, through: :role_policies
  has_many :managed_roles, through: :role_policies
  belongs_to :unit, optional: true
  belongs_to :school, optional: true
  belongs_to :phase, optional: true

  def can_manage?(user)
    managed_roles.include?(user.role)
  end

  def admin?
    role.admin?
  end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :type)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/colleges/_form.html.erb
<%= form_for(college) do |f| %>
  <% if college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colleges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.type %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @college.type %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>