config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'unauthorized' => 'home#unauthorized'

  get 'home/license'

  resources :phase_roles
  resources :phases
  resources :sections
  resources :role_policies
  resources :recusals
  resources :uploads
  resources :divisions
  resources :departments
  resources :units
  resources :branches
  resources :colleges
  resources :schools
  resources :roles
  resources :user_roles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/branch.rb
class Branch < School
end

app/models/college.rb
class College < School
end

app/models/department.rb
class Department < Unit
end

app/models/division.rb
class Division < Unit
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :next_phase, class_name: 'Phase'
  has_one :previous_phase, as: :next_phase
  has_many :phase_roles
  has_many :roles, through: :phase_roles
end

app/models/phase_role.rb
class PhaseRole < ApplicationRecord
  belongs_to :phase
  belongs_to :role
end

app/models/recusal.rb
class Recusal < ApplicationRecord
  belongs_to :reviewer,  class_name: 'UserRole'
  belongs_to :candidate, class_name: 'UserRole'
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
  has_many :role_policies
  has_many :administrator_roles, through: :role_policies
  has_many :managed_roles, through: :role_policies
  has_many :phase_roles
  has_many :phases, through: :phase_roles
end

app/models/role_policy.rb
class RolePolicy < ApplicationRecord
  belongs_to :administrator_role, class_name: 'Role'
  belongs_to :managed_role, class_name: 'Role'
end

app/models/school.rb
class School < ApplicationRecord
  has_many :units
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :role
  has_many :uploads
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :school
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  belongs_to :section
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :uploads
  has_many :recusals, as: :reviewer
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
  has_many :role_policies, through: :role
  has_many :administrator_roles, through: :role_policies
  has_many :managed_roles, through: :role_policies
  belongs_to :unit, optional: true
  belongs_to :school, optional: true
  belongs_to :phase, optional: true

  def can_manage?(user)
    managed_roles.include?(user.role)
  end

  def admin?
    role.admin?
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:school_id, :name, :type)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/units/_form.html.erb
<%= form_for(unit) do |f| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_id %>
    <%= f.text_field :school_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.school %></td>
        <td><%= unit.name %></td>
        <td><%= unit.type %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @unit.school %>
</p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @unit.type %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>